# Generated by Django 5.2.1 on 2025-05-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_orders', models.IntegerField()),
                ('delivered_orders', models.IntegerField()),
                ('compliance_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='hospitals.hospital')),
            ],
        ),
    ]
